Make sure wmctrl is available.

diff --git a/scripts/all/gr b/scripts/all/gr
--- a/scripts/all/gr
+++ b/scripts/all/gr
@@ -9,6 +9,11 @@ fi
 extraopts=""
 if [[ "$OS" == "linux" ]]; then
     extraopts="--name GVIM0"
+
+    type -a wmctrl 2>&1 > /dev/null || {
+        echo 2>&1 "ERROR: please install wmctrl" ;
+        exit 1 ;
+    }
 fi
 
 if [[ "$OS" == "darwin" ]]; then
