git-clean-branches: be a bit more robust
We now avoid deleting the branch you are on when using `--auto`.  Also,
be more robust in handling the command line options.  Finally, if the
user provides a branch name, attempt to use it as the base to compare
against.  However, if must be an "approved" name to avoid accidentally
causing damage to the repository.

diff --git a/git-addons/git-clean-branches b/git-addons/git-clean-branches
--- a/git-addons/git-clean-branches
+++ b/git-addons/git-clean-branches
@@ -34,34 +34,48 @@ function check_ref()
     return 1
 }
 
+while :
+do
+    case "$1" in
+        -n)
+            shift
+            DRY_RUN="echo"
+            ;;
+        --auto)
+            shift
+            REF="$(determine_ref)" || die "ERROR: Couldn't determine mainline branch."
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
 
-if [ "$1" = "-n" ]
+if [ -z "$REF" ]
 then
-    shift
-    DRY_RUN=echo
+    if [ -n "$1" ]
+    then
+        REF="$(git symbolic-ref --short HEAD)"
+    else
+        REF="$1"
+    fi
 fi
-
-if [ "$1" = "--auto" ]
-then
-    shift
-    REF="$(determine_ref)" || die "ERROR: Couldn't determine mainline branch."
-else
-    REF="$(git symbolic-ref --short HEAD)"
-fi
-
 
 if ! check_ref "$REF"
 then
     die "ERROR: Not on an acceptable branch (master, dev, develop, development)"
 fi
 
+CURRENT_BRANCH="$(git symbolic-ref --short HEAD)"
+
 # Need to find a way to handle "git branch -d" with it's safety
 # mechanism.  At the moment, it'll complain if a branch is not merged
 # to whatever branch we have checked out, which is why we require master
 # right now.
-git branch -a --merged "$REF" |
-    egrep -v '^(\* |[ \t]*|.*/remotes)([0-9]+\.[0-9]+\.x|master|develop|development|HEAD|integrate|remotes/.*)$' |
-    egrep -v "$REF" |
+git branch -a --format="%(refname:short)" --merged "$REF" |
+    egrep -v '^(\* |[ \t]*|.*/remotes)([0-9]+\.[0-9]+\.x|master|develop|development|HEAD|integrate|.*(\b|_)test(\b|_).*|remotes/.*)$' |
+    egrep -v "^$REF\$" |
+    egrep -v "^$CURRENT_BRANCH\$" |
     while read -r branch
     do
         ${DRY_RUN} git branch -d "$branch"
