git-missing: print ERROR from within die

diff --git a/git-addons/git-missing b/git-addons/git-missing
--- a/git-addons/git-missing
+++ b/git-addons/git-missing
@@ -11,7 +11,7 @@
 die_with_status () {
     status=$1
     shift
-    echo >&2 "$*"
+    echo >&2 "ERROR: $*"
     exit "$status"
 }
 
@@ -22,7 +22,7 @@ die () {
 firstbranch=$1
 secondbranch=$2
 
-git rev-parse --git-dir > /dev/null 2>&1 || die "ERROR: Not in a git repo"
+git rev-parse --git-dir > /dev/null 2>&1 || die "Not in a git repo"
 
 if test -z "$firstbranch"; then
     # Compare against the tracking branch...
