completion: introduce _make_dir_complete helper
This function can be used to help create aliases that cd to a directory,
but also can cd into sub-directories, and offer completion.

diff --git a/zsh/zshenv b/zsh/zshenv
--- a/zsh/zshenv
+++ b/zsh/zshenv
@@ -11,6 +11,35 @@ setopt glob		    # want globbing
 unsetopt nomatch	    # don't warn about non-matching globs
 setopt pushd_silent         # don't print stack after push/pop
 
+# A function to help with creating directory aliases and providing
+# completion for them.
+# Taken from here:
+#   https://github.com/caio/oh-my-zsh/blob/master/plugins/make-dir-complete/make-dir-complete.plugin.zsh
+_make_dir_complete() {
+    if [ ${#} -ne 2 ]; then
+        echo "usage: make_dir_complete <new-alias-name> <path>" 1>&2
+        return 1
+    fi
+
+    local aliasname=$1
+
+    if type $aliasname >/dev/null 2>&1; then
+        echo "Error: can't overwrite previously defined command \"$1\"" 1>&2
+        return 1
+    fi
+    if [ ! -d $2 ]; then
+        echo "Error: \"$2\" doesn't point to a directory" 1>&2
+    fi
+
+    cd "$2" >/dev/null 2>&1
+    local dirname=$(pwd -P)
+    cd - >/dev/null 2>&1
+
+    FUNC="$aliasname () { cd $dirname/\$@ }"
+    eval $FUNC
+    compctl -/ -W $dirname $aliasname
+}
+
 test -s "$ETC_HOME/shell-common/functions.sh" &&
 	. $ETC_HOME/shell-common/functions.sh
 test -s "$ETC_HOME/shell-common/exports.sh" &&
